---
- name: Istalling Packages 
  hosts: targets  # Replace with your target host or group
    #  become: true  # To escalate privileges
  remote_user: root
  gather_facts: no
    #become_method: sudo
  
  tasks:
    - name: "Install common software packages"
      become: true
      yum:
       name:
        - sysstat
        - net-tools
        - unzip
        - tar
        - yum-utils
        - wget
        - telnet
        - openscap-scanner
        - bzip2
        - dnf-automatic
      state: present
      disable_plugin: fastestmirror
    ignore_errors: yes
